# -*- coding: utf-8 -*-
"""hough_features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EMQBHko9LCmS68BI_5UIxBcJifcu_2Tp
"""

import numpy as np
import cv2
from skimage.transform import hough_line, hough_line_peaks
def calculate_hough_features(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 50, 150, apertureSize=3)
    h, theta, d = hough_line(edges)
    _, angles, dists = hough_line_peaks(h, theta, d)
    avg_angle = np.mean(angles)
    avg_dist = np.mean(dists)
    return avg_angle, avg_dist